### env
#
# WEBSERVER_FQDN
# NODE_HOSTNAME
#
version: '3.8'
services:
  jenkins:
    image: jenkins/jenkins:latest
    user: root
    environment:
      TZ: America/Sao_Paulo
    volumes:
      - home:/var/jenkins_home
      - hooks:/autodeploy-jenkins-hooks
      - /var/lib/docker/volumes:/docker-volumes
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - web
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          memory: 6G
      placement:
        constraints:
          - node.hostname == ${NODE_HOSTNAME}
      labels:
      - traefik.enable=true
      - traefik.port=8080
      - traefik.frontend.rule=Host:${WEBSERVER_FQDN}
      - traefik.protocol=http
      - traefik.docker.network=web

volumes:
  home:
    driver: local
  hooks:
    driver: local
    
networks:
   web:
     external:
       name: web